# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7fbeb8be68363e7381c350ad7b421afe"
name = "free-shipping-bar"
application_url = "https://free-shipping-bar-production-ffdd.up.railway.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks"
  topics = [ "app/uninstalled" ]

[access_scopes]
scopes = "read_orders"

[auth]
redirect_urls = [
  "https://free-shipping-bar-production-ffdd.up.railway.app/auth/callback",
  "https://free-shipping-bar-production-ffdd.up.railway.app/auth/shopify/callback"
]
